---

- name: Unarchive nignx packages.
  unarchive:
    remote_src: false
    src: "{{ nginx_package }}"
    dest: /usr/local/src

- name: create nginx install directory
  file:
    path: "{{ nginx_install_dir }}"
    state: directory

- name: install nginx depedent packages.
  yum: name="{{ item }}" state=present
  loop: "{{ nginx_depedent_packages }}"

- name: Compiled nginx file.
  command: >-
         ./configure --prefix={{ nginx_install_dir}}  --with-pcre 
         --with-http_stub_status_module --with-http_ssl_module
         --with-http_secure_link_module
         --add-module=/opt/install/websockify-nginx-module-master 
  args:
    chdir: /usr/local/src/nginx-{{ nginx_verison }}

- name: Make nginx file.
  command: make -j{{ ansible_processor_cores|default(1) + 1 }}
  args:
    chdir: /usr/local/src/nginx-{{ nginx_verison }}

- name: Instal nginx.
  command: make install
  args:
    chdir: /usr/local/src/nginx-{{ nginx_verison }}

- name: Ensure nginx service can running.
  command: ./nginx
  args:
    chdir: "{{ nginx_install_dir }}/sbin"
  register: result

- name: Ensure nginx service can running.
  command: ./nginx -s stop
  args:
    chdir: "{{ nginx_install_dir }}/sbin"
  when: result.changed
