---

- name: Configure nginx.
  template:
    remote_src: false
    src: nginx.conf
    dest: "{{ nginx_install_dir }}conf/nginx.conf"

- name: Ensure nginx service can running.
  command: ./nginx -t {{ nginx_install_dir }}/conf/nginx.conf
  args:
    chdir: "{{ nginx_install_dir }}sbin"

- name: Configure nginx service.
  copy:
    remote_src: false
    src: nginx.service
    dest: /usr/lib/systemd/system/nginx.service
  notify:
    - start nginx
